name = "notion"
type = "javascript"
zone_id = ""
account_id = "1ce6900d3edc12b4d953942ca4d5078f"
route = ""
workers_dev = true

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
